# -*- coding: utf-8 -*-
"""Progetto_ICON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tMR2o11J5TpiPpseglgRHo-ti_U9DfEp

# Installazioni e importazioni
"""

#Installazioni

!pip install imbalanced-learn
!pip install pgmpy pandas
!apt-get install -y swi-prolog
!pip install pyswip

#Importazione delle librerie

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV, KFold
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.metrics import classification_report, accuracy_score,confusion_matrix
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.estimators import MaximumLikelihoodEstimator, BayesianEstimator, HillClimbSearch, BIC
from pgmpy.inference import VariableElimination
from sklearn.ensemble import RandomForestClassifier
from pyswip import Prolog
import matplotlib.pyplot as plt
import seaborn as sns

"""# Preparazione del dataset"""

#Importazione del dataset dal csv

df = pd.read_csv("/content/google_books_1299.csv")

#Visualizzazione delle colonne del DataFrame e delle informazioni sui loro tipi

print(df.columns)
df.info()

#Eliminazione delle colonne considerate superflue per le fasi successive

df.drop(['Unnamed: 0', 'price', 'currency', 'language', 'published_date'],axis=1, inplace=True)
#language è considerata superflua perchè il dataset contiene solo libri in lingua inglese

#Rimozione dei duplicati basata sul titolo e sull'autore
df['title_clean'] = df['title'].str.lower().str.strip()
df['author_clean'] = df['author'].str.lower().str.strip()
df = df.drop_duplicates(subset=['title_clean', 'author_clean'], keep='first')
df = df.drop(columns=['title_clean', 'author_clean']).reset_index(drop=True)

print(f"Duplicati rimossi! Righe rimanenti: {len(df)}")

#Normalizzazione dei valori della colonna voters

df['voters'] = df['voters'].fillna('0') #rimuoviamo i valori nulli, sostituiti con degli 0
df['voters'] = df['voters'].str.replace(',', '') #rimuoviamo la virgola dove presente
df['voters'] = df['voters'].astype(int) #conversione in numeri interi

#Normalizzazione dei valori della colonna rating

df['rating'] = df['rating'].fillna(0)

#Aggiunta di una colonna contenente il rapporto fra il numero di votanti e la valutazione
#media del libro e normalizzazione del risultato sostituendo i valori nulli con uno zero

df['voters/rating'] = df['voters'] / df['rating']
df['voters/rating'] = np.ceil(df['voters/rating'].fillna(0))

#Eliminazione delle colonne rating e voters che non servono più

df.drop(['rating', 'voters'],axis=1, inplace=True)

#Normalizzazione del valore del genere per i libri per i quali non è specificato alcun genere

df['generes'] = df['generes'].str.replace('none', 'Unknown')
df['generes'] = df['generes'].fillna('Unknown')

#Assumendo che un libro possa avere 3 generi al massimo e che i generi siano forniti in ordine
#di rilevanza, si creano 3 nuove colonne, una per ogni genere, per poterli trattare come feature
#separate. Si elimina poi la vecchia colonna generes

generi_split = df['generes'].str.split(',', expand=True)
df['genere_1'] = generi_split[0].str.strip().fillna('Unknown')
if 1 in generi_split.columns:
    df['genere_2'] = generi_split[1].str.strip().fillna('Unknown')
else:
    df['genere_2'] = 'Unknown'
if 2 in generi_split.columns:
    df['genere_3'] = generi_split[2].str.strip().fillna('Unknown')
else:
    df['genere_3'] = 'Unknown'
df=df.drop('generes', axis=1)

#Categorizzazione del numero di pagine (Corto, Medio, Lungo)
df['page_count'] = pd.cut(df['page_count'], bins=[0, 200, 500, 2000], labels=['short', 'medium', 'long'])
df['page_count'] = df['page_count'].cat.add_categories('Unknown').fillna('Unknown')

#Categorizzazione del rating
df['voters/rating'] = pd.qcut(df['voters/rating'], q=4, labels=['low', 'average', 'high', 'top'])

#Aggiunta al DataFrame di una colonna in cui segnare se all'utente piace o meno il libro

df['liked'] = ''

#Scelta dei generi di interesse da usare come profilo dei gusti di un utente fittizio,
#così da generare in maniera realistica i dati per compilare la colonna liked

gusti = ['fiction', 'fantasy', 'mystery &amp', 'graphic novels']

#Generazione dei valori per compilare la colonna liked

gusti_set=set(gusti)
for id, row in df.iterrows():
    generi_libro = [str(row['genere_1']).lower(),
                    str(row['genere_2']).lower(),
                    str(row['genere_3']).lower()]
    match = not gusti_set.isdisjoint(generi_libro)
    if match:
      prob=(0.9, 0.1)
    else:
      prob=(0.1, 0.9)
    df.loc[id, 'liked'] = np.random.choice(['yes', 'no'], p=prob)

#caricamento di un dataset precedente ai fini di mostrare risultati stabili.
#Le precedenti celle sono presenti per mostrare le procedure di feature engeneering effettuate

df = pd.read_csv("dataset_books.csv")

#Divisione del DataFrame in Train e Test set

train, test = train_test_split(df, test_size=0.2, random_state=42, stratify=df['liked'])

"""# Albero Decisionale"""

#Selezione delle features utili all'albero e creazione dei Train e Test set

features = ['author', 'publisher', 'page_count', 'genere_1', 'genere_2', 'genere_3', 'voters/rating']
X_train= train[features]
y_train = train['liked']
X_test= test[features]
y_test = test['liked']

#Creazione della pipeline per eseguire l'encoding e la classificazione implementando SMOTE
pipeline_smote = ImbPipeline(steps=[('encoder', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)),
                                    ('smote', SMOTE(random_state=42)),
                                    ('classifier', DecisionTreeClassifier(random_state=42))])

#Ricerca dei parametri migliori per l'albero tramite una gridsearch

#Definizione dei parametri da esplorare
param_grid = {
    'classifier__max_depth': [3, 5, 7, 10, None],
    'classifier__min_samples_split': [2, 5, 10],
    'classifier__criterion': ['gini', 'entropy'],
    'smote__k_neighbors': [3, 5]}

#Creazione del ricercatore
grid_smote = GridSearchCV(pipeline_smote, param_grid, cv=5, scoring='f1_weighted')

#Avvio dell'addestramento
grid_smote.fit(X_train, y_train)

#Stampa dei migliori risultati
print(f"Migliori parametri trovati (con SMOTE): {grid_smote.best_params_}")

#Prelievo del modello migliore
y_pred_best = grid_smote.best_estimator_.predict(X_test)

#Stampa del report di classificazione
print("\nREPORT DI CLASSIFICAZIONE - ALBERO DECISIONALE")
print(classification_report(y_test, y_pred_best))

# Generazione della matrice di confusione
cm = confusion_matrix(y_test, y_pred_best)

# Visualizzazione della matrice di confusione
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=grid_smote.best_estimator_.classes_,
            yticklabels=grid_smote.best_estimator_.classes_)
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Matrice di Confusione per Albero Decisionale')
plt.show()

"""# Rete Bayiesiana (Naive Bayes)"""

#Ricerca della struttura migliore

hc = HillClimbSearch(train)
best_model_structure = hc.estimate(scoring_method=BIC(train))
print("Archi della struttura ottimale:", best_model_structure.edges())

#Creazione del modello sulla base della struttura trovata al passo precedente

bayesian_network_model = DiscreteBayesianNetwork(best_model_structure.edges())

#Addestramento del modello

bayesian_network_model.fit(train, estimator=BayesianEstimator, prior_type="BDeu")

#Test del modello

#Inizializzazione dell'oggetto per l'inferenza
inference = VariableElimination(bayesian_network_model)

# Raccolta della lista dei nodi che fanno parte della rete
network_nodes = bayesian_network_model.nodes()

#Raccolta della lista degli stati che la rete conosce per ogni nodo
state_names = bayesian_network_model.get_cpds('liked').state_names

#Definizione di una funzione per effettuare la predizione su una riga
def predict_book(row):
    evidence = {}
    for node in bayesian_network_model.nodes():
        if node != 'liked':
            valore_test = row[node]
            # Si ottiene la lista dei valori che la rete conosce per questo specifico nodo
            stati_conosciuti = bayesian_network_model.get_cpds(node).state_names[node]

            #Se il valore nel test non è tra quelli conosciuti, non lo si passa come evidence (la rete userà la probabilità a priori)
            if valore_test in stati_conosciuti:
                evidence[node] = valore_test
            else:
                pass
    if not evidence:
        return 'unknown'
    try:
        prediction = inference.map_query(variables=['liked'], evidence=evidence, show_progress=False)
        return str(prediction['liked'])
    except Exception:
        return 'error'

#Esecuzione della funzione sul test set
test['prediction'] = test.apply(predict_book, axis=1)

#Pulizia delle stringhe prima della valutazione
test['liked'] = test['liked'].astype(str).str.lower().str.strip()
test['prediction'] = test['prediction'].astype(str).str.lower().str.strip()

#Stampa del report di classificazione
print("\nREPORT DI CLASSIFICAZIONE - RETE BAYESIANA")
print(classification_report(test['liked'], test['prediction']))

# Generazione della matrice di confusione per la Rete Bayesiana
cm_bn = confusion_matrix(test['liked'], test['prediction'])

# Visualizzazione della matrice di confusione
plt.figure(figsize=(8, 6))
sns.heatmap(cm_bn, annot=True, fmt='d', cmap='Blues',
            xticklabels=['no', 'yes'],
            yticklabels=['no', 'yes'])
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Matrice di Confusione per Rete Bayesiana')
plt.show()

"""# Logica Proposizionale"""

#Creazione della Knowledge Base (Estrazione dei fatti)

#Definizione della funzione per rendere i testi compatibili con Prolog (trasforma in minuscolo, toglie spazi e caratteri non alfanumerici)
def clean_for_prolog(text):
    if pd.isna(text): return "unknown"
    clean = "".join(e for e in str(text).lower() if e.isalnum() or e == '_')
    return clean if clean else "unknown"

# Generazione del file .pl contenete la knowledge base
with open('conoscenza_libri.pl', 'w') as f:
    for _, row in df.iterrows():
        # Estrazione dei dati dal dataframe pulito
        titolo = clean_for_prolog(row['title'])
        autore = clean_for_prolog(row['author'])
        g1 = clean_for_prolog(row['genere_1'])
        g2 = clean_for_prolog(row['genere_2'])
        g3 = clean_for_prolog(row['genere_3'])
        pagine = row['page_count']
        rapporto = row['voters/rating']
        liked = row['liked']

        # Scrittura del fatto nel file f
        fatto = f"libro({titolo}, {autore}, '{g1}', '{g2}', '{g3}', {pagine}, {rapporto}, {liked}).\n"
        f.write(fatto)

print("File conoscenza_libri.pl generato con successo!")

# Caricamento dei file contenenti i fatti e le regole

prolog = Prolog()
prolog.consult("conoscenza_libri.pl")
prolog.consult("regole.pl")

# Esecuzione di una query: ricerca di tutti i titoli 'consigliati'
results = list(prolog.query("consigliato(Titolo)"))

# Stampa dei risultati
print("\nLIBRI CONSIGLIATI DALLA LOGICA PROPOSIZIONALE")
for res in results:
    print(f"- {res['Titolo']}")

#Test del modello

def predict_prolog(row):
    #Pulizia della stringa titolo
    titolo_pulito = "".join(e for e in str(row['title']).lower() if e.isalnum() or e == '_')

    #Si interroga il Prolog: il libro è 'consigliato'?
    query = f"consigliato('{titolo_pulito}')"
    result = list(prolog.query(query))

    # Se la query restituisce almeno un risultato, Prolog dice 'yes'
    return 'yes' if len(result) > 0 else 'no'

# Si applica la funzione al test set
test_df = df.loc[test.index].copy()
test_df['prolog_pred'] = test_df.apply(predict_prolog, axis=1)

#Stampa del report di classificazione
print("\nREPORT DI CLASSIFICAZIONE - LOGICA PROPOSIZIONALE")
print(classification_report(test_df['liked'], test_df['prolog_pred']))

# Generazione della matrice di confusione per la Logica Proposizionale
cm_prolog = confusion_matrix(test_df['liked'], test_df['prolog_pred'])

# Visualizzazione della matrice di confusione
plt.figure(figsize=(8, 6))
sns.heatmap(cm_prolog, annot=True, fmt='d', cmap='Blues',
            xticklabels=['no', 'yes'],
            yticklabels=['no', 'yes'])
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Matrice di Confusione per Logica Proposizionale')
plt.show()

"""# Random Forest"""

#Creazione della pipeline per eseguire l'encoding e la classificazione implementando SMOTE

random_forest_model = ImbPipeline(steps=[('encoder', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)),
                                         ('smote', SMOTE(random_state=42)),
                                         ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))])

#Definizione dei parametri da esplorare
param_grid = {
    'classifier__n_estimators': [50, 100, 200],
    'classifier__max_depth': [None, 10, 20],
    'classifier__min_samples_split': [2, 5, 10],
    'classifier__criterion': ['gini', 'entropy']
}

#Creazione del ricercatore
grid_search = GridSearchCV(
    estimator=random_forest_model,
    param_grid=param_grid,
    cv=5,
    scoring='f1_weighted',
    n_jobs=-1
)

#Avvio dell'addestramento
grid_search.fit(X_train, y_train)

#Stampa dei migliori risultati
print(f"Migliori parametri trovati: {grid_search.best_params_}")

#Prelievo del modello migliore
best_rf_model = grid_search.best_estimator_
y_pred_best = best_rf_model.predict(X_test)

#Stampa del report di classificazione
print("\nREPORT DI CLASSIFICAZIONE - RANDOM FOREST")
print(classification_report(y_test, y_pred_best))

# Generazione della matrice di confusione per la Random Forest
cm_rf = confusion_matrix(y_test, y_pred_best)

# Visualizzazione della matrice di confusione
plt.figure(figsize=(8, 6))
sns.heatmap(cm_rf, annot=True, fmt='d', cmap='Blues',
            xticklabels=best_rf_model.classes_,
            yticklabels=best_rf_model.classes_)
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Matrice di Confusione per Random Forest')
plt.show()

"""# Confronto fra i modelli"""

#Preparazione delle liste per i risultati
modelli = ['Albero Decisionale', 'Random Forest', 'Rete Bayesiana', 'Prolog']
risultati = {nome: [] for nome in modelli}

#Definizione della KFold Cross-Validation con 10 fold
kf = KFold(n_splits=10, shuffle=True, random_state=42)

for train_index, test_index in kf.split(df):
    df_train, df_test = df.iloc[train_index], df.iloc[test_index]
    X_train_cv = df_train[features]
    y_train_cv = df_train['liked']
    X_test_cv = df_test[features]
    y_test_cv = df_test['liked']

    #ALBERO DECISIONALE
    # Si usa il miglior stimatore trovato dalla GridSearch
    grid_smote.best_estimator_.fit(X_train_cv, y_train_cv)
    p_dt = grid_smote.best_estimator_.predict(X_test_cv)
    risultati['Albero Decisionale'].append(accuracy_score(y_test_cv, p_dt))

    #RANDOM FOREST
    # Si usa il miglior stimatore della GridSearch RF
    grid_search.best_estimator_.fit(X_train_cv, y_train_cv)
    p_rf = grid_search.best_estimator_.predict(X_test_cv)
    risultati['Random Forest'].append(accuracy_score(y_test_cv, p_rf))

    #RETE BAYESIANA
    bn_model = DiscreteBayesianNetwork(best_model_structure.edges())
    bn_model.fit(df_train, estimator=BayesianEstimator, prior_type="BDeu")
    p_bn = df_test.apply(predict_book, axis=1)
    p_bn_clean = p_bn.astype(str).str.lower().str.strip()
    y_test_clean = y_test_cv.astype(str).str.lower().str.strip()
    risultati['Rete Bayesiana'].append(accuracy_score(y_test_clean, p_bn_clean))

    #LOGICA PROPOSIZIONALE
    p_prolog = df_test.apply(predict_prolog, axis=1)
    risultati['Prolog'].append(accuracy_score(y_test_clean, p_prolog))

#Calcolo delle medie e delle deviazioni standard (Varianza)
medie = [np.mean(risultati[n]) for n in modelli]
deviazioni = [np.std(risultati[n]) for n in modelli]

#Creazione e stampa del Grafico a Barre
plt.figure(figsize=(12, 7))
colori = ['#3498db', '#2ecc71', '#f1c40f', '#e74c3c']
barre = plt.bar(modelli, medie, yerr=deviazioni, capsize=8, color=colori, edgecolor='black', alpha=0.8)
plt.ylabel('Accuratezza Media (CV)')
plt.title('Confronto Finale Modelli: Accuratezza e Stabilità')
plt.ylim(0, 1.0)
plt.grid(axis='y', linestyle='--', alpha=0.3)
for i, bar in enumerate(barre):
    plt.text(bar.get_x() + bar.get_width()/2, medie[i] + 0.02, f'{medie[i]:.2f}', ha='center', fontweight='bold')
plt.show()